refactor: dotfiles cli

diff --git a/cli/dotf/dotf b/cli/dotf/dotf
--- a/cli/dotf/dotf
+++ b/cli/dotf/dotf
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.0.3 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.0.4 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -34,6 +34,7 @@ dotf_usage() {
     echo
     # :command.usage_commands
     printf "%s\n" "Commands:"
+    printf "  %s   Make symbol link for packages\n" "link  "
     printf "  %s   sync or export layout of the directory\n" "layout"
     echo
 
@@ -47,6 +48,68 @@ dotf_usage() {
         echo
         printf "  %s\n" "--version, -v"
         printf "    Show version number\n"
+        echo
+
+    fi
+}
+
+# :command.usage
+dotf_link_usage() {
+    if [[ -n $long_usage ]]; then
+        printf "dotf link - Make symbol link for packages\n"
+        echo
+
+    else
+        printf "dotf link - Make symbol link for packages\n"
+        echo
+
+    fi
+
+    printf "%s\n" "Usage:"
+    printf "  dotf link [OPTIONS]\n"
+    printf "  dotf link --help | -h\n"
+    echo
+
+    # :command.long_usage
+    if [[ -n $long_usage ]]; then
+        printf "%s\n" "Options:"
+
+        # :command.usage_flags
+        # :flag.usage
+        printf "  %s\n" "--delete, -D"
+        printf "    Unstow the package names that follow this option\n"
+        echo
+
+        # :flag.usage
+        printf "  %s\n" "--restow, -R"
+        printf "    Restow (like stow -D followed by stow -S)\n"
+        echo
+
+        # :flag.usage
+        printf "  %s\n" "--adopt"
+        printf "    (Use with care!)  Import existing files into stow package from target.\n    Please read stow docs before using.\n"
+        echo
+
+        # :flag.usage
+        printf "  %s\n" "--simulate, -n"
+        printf "    Do not actually make any filesystem changes\n"
+        echo
+
+        # :flag.usage
+        printf "  %s\n" "--verbose, -v"
+        printf "    Verbose output\n"
+        echo
+
+        # :command.usage_fixed_flags
+        printf "  %s\n" "--help, -h"
+        printf "    Show this help\n"
+        echo
+
+        # :command.usage_examples
+        printf "%s\n" "Examples:"
+        printf "  dotf link -v\n"
+        printf "  dotf link -v -n\n"
+        printf "  dotf link -v -n --adopt\n"
         echo
 
     fi
@@ -249,6 +312,95 @@ inspect_args() {
 }
 
 # :command.user_lib
+# src/lib/cmd/link.sh
+dotf::link::stow_log() {
+    if [[ $? -eq 0 ]]; then
+        local result="$(green_bold OK)"
+    else
+        local result="$(red_bold ERROR)"
+    fi
+    printf "stow %-12s [ %s ]\n" "$1" "${result}"
+}
+
+dotf::link::stow_make() {
+    local flags=()
+    if dotf::utils::boolean::is_true ${args[--delete]}; then
+        flags+=("-D")
+    fi
+    if dotf::utils::boolean::is_true ${args[--restow]}; then
+        flags+=("-R")
+    fi
+    if dotf::utils::boolean::is_true ${args[--adopt]}; then
+        flags+=("--adopt")
+    fi
+    if dotf::utils::boolean::is_true ${args[--simulate]}; then
+        flags+=("-n")
+    fi
+    if dotf::utils::boolean::is_true ${args[--verbose]}; then
+        flags+=("-v")
+    fi
+    local opt=$(
+        IFS=" "
+        echo "${flags[*]}"
+    )
+    stow ${opt} -d "${DOTF_LINK_STOW_SRC}" -t "${DOTF_LINK_STOW_TARGET}" "$1"
+}
+
+dotf::link::pkg_is_exclude() {
+    [[ ":${DOTF_LINK_EXCLUDE_PACKAGES_STRING}:" == *":$1:"* ]]
+}
+
+dotf::link::pkg_stow() {
+    dotf::link::stow_make stow
+}
+
+dotf::link::pkg_brew() {
+    dotf::link::stow_make brew
+}
+
+dotf::link::pkg_go() {
+    dotf::link::stow_make go
+}
+
+dotf::link::pkg_conda() {
+    dotf::link::stow_make conda
+}
+
+dotf::link::pkg_zsh() {
+    # local zfiles=(.zprofile .zshenv .zshrc)
+    # for v in "${zfiles[@]}"; do
+    #     local filepath="${HOME}/${v}"
+    #     if [[ ! -L "${filepath}" ]]; then
+    #         rm -f "${filepath}"
+    #         echo "Delete ${filepath}"
+    #     fi
+    # done
+    dotf::link::stow_make zsh
+}
+
+dotf::link::pkg_python() {
+    dotf::link::stow_make python
+}
+
+dotf::link::pkg_deps() {
+    dotf::link::pkg_stow
+    dotf::link::pkg_brew
+    dotf::link::pkg_go
+    dotf::link::pkg_conda
+    dotf::link::pkg_zsh
+    dotf::link::pkg_python
+}
+
+dotf::link::packages() {
+    find "${DOTF_LINK_STOW_SRC}" -maxdepth 1 -mindepth 1 -type d | sort | while read name; do
+        local pkg=$(basename "${name}")
+        if ! dotf::link::pkg_is_exclude "${pkg}"; then
+            dotf::link::stow_make "${pkg}"
+            dotf::link::stow_log "${pkg}"
+        fi
+    done
+}
+
 # src/lib/colors.sh
 print_in_color() {
     local color="$1"
@@ -282,12 +434,22 @@ magenta_underlined() { print_in_color "\e[4;35m" "$*"; }
 cyan_underlined() { print_in_color "\e[4;36m" "$*"; }
 
 # src/lib/consts.sh
-DOTF_ROOT="${HOME}/.dotfiles"
+# Global
+DOTF_ROOT="${DOTFILES_ROOT:-${HOME}/.dotfiles}"
 DOTF_PKG_DIR="${DOTF_ROOT}/packages"
 DOTF_LAYOUT_DIR="${DOTF_PKG_DIR}/os/layouts"
 
+# Link
+DOTF_LINK_STOW_SRC="${DOTF_PKG_DIR}"
+DOTF_LINK_STOW_TARGET="${HOME}"
+DOTF_LINK_EXCLUDE_PACKAGES=(.git .venv .vscode)
+DOTF_LINK_EXCLUDE_PACKAGES_STRING=$(
+    IFS=:
+    echo "${DOTF_LINK_EXCLUDE_PACKAGES[*]}"
+)
+
 # src/lib/message.sh
-utils::message::format() {
+dotf::utils::message::format() {
     local prefix="$1"
     shift
     local format="$1"
@@ -295,30 +457,36 @@ utils::message::format() {
     printf "${prefix}: ${format}\n" "$@"
 }
 
-utils::message::info() {
-    local msg="$(utils::message::format "INFO" "$@")"
+dotf::utils::message::info() {
+    local msg="$(dotf::utils::message::format "INFO" "$@")"
     green "${msg}"
 }
 
-utils::message::warning() {
-    local msg="$(utils::message::format "WARNING" "$@")"
+dotf::utils::message::warning() {
+    local msg="$(dotf::utils::message::format "WARNING" "$@")"
     yellow "${msg}"
 }
 
-utils::message::error() {
-    local msg="$(utils::message::format "ERROR" "$@")"
+dotf::utils::message::error() {
+    local msg="$(dotf::utils::message::format "ERROR" "$@")"
     red "${msg}" >&2
 }
 
-utils::message::fatal() {
-    utils::message::error "$@"
+dotf::utils::message::fatal() {
+    dotf::utils::message::error "$@"
     exit 1
 }
 
+# src/lib/os.sh
+dotf::os::platform::is_arm64() {
+    local arch="$(uname -m)"
+    [[ "${arch}" == "arm64" || "${arch}" == "aarch64" ]]
+}
+
 # src/lib/utils.sh
-utils::boolean::is_true() {
+dotf::utils::boolean::is_true() {
     case "$1" in
-        true | yes | 1)
+        true | yes | 1 | "1")
             true
             return
             ;;
@@ -329,9 +497,9 @@ utils::boolean::is_true() {
     esac
 }
 
-utils::boolean::is_false() {
+dotf::utils::boolean::is_false() {
     case "$1" in
-        false | no | 0)
+        false | no | 0 | "0")
             true
             return
             ;;
@@ -343,10 +511,18 @@ utils::boolean::is_false() {
 }
 
 # :command.command_functions
+# :command.function
+dotf_link_command() {
+    # src/cmd/link.sh
+    # inspect_args
+    dotf::link::pkg_deps
+    dotf::link::packages
+
+}
 
 # :command.function
 dotf_layout_git_command() {
-    # src/layout/git.sh
+    # src/cmd/layout/git.sh
     local path="${args[path]%/}"
     local output="${args[--output]}"
     local layout="${args[--layout]}"
@@ -357,11 +533,11 @@ dotf_layout_git_command() {
         if [[ -n "${layout}" ]]; then
             output="${DOTF_LAYOUT_DIR}/${layout}"
         else
-            utils::message::fatal "missing --output or --layout, please see --help for detail."
+            dotf::utils::message::fatal "missing --output or --layout, please see --help for detail."
         fi
     fi
 
-    if ! utils::boolean::is_true "${dry_run}"; then
+    if ! dotf::utils::boolean::is_true "${dry_run}"; then
         local output_dir="$(dirname "${output}")"
         mkdir -p "${output_dir}"
         # Clear layout file content
@@ -372,8 +548,8 @@ dotf_layout_git_command() {
         local filedir=$(dirname "${filename}")
         local url="$(git -C "${filedir}" config --get remote.origin.url)"
         local target="${filedir/#${HOME}/\~}"
-        if utils::boolean::is_true "${dry_run}"; then
-            utils::message::warning "[Simulate] ${target} ==> ${url}"
+        if dotf::utils::boolean::is_true "${dry_run}"; then
+            dotf::utils::message::warning "[Simulate] ${target} ==> ${url}"
         else
             local line="${target};${url}\n"
             printf "${line}" >>"${output}"
@@ -384,7 +560,7 @@ dotf_layout_git_command() {
 
 # :command.function
 dotf_layout_sync_command() {
-    # src/layout/sync.sh
+    # src/cmd/layout/sync.sh
     local source="${args[--source]}"
     local layout="${args[--layout]}"
     local dry_run="${args["--dry-run"]}"
@@ -393,11 +569,11 @@ dotf_layout_sync_command() {
         if [[ -n "${layout}" ]]; then
             source="${DOTF_LAYOUT_DIR}/${layout}"
         else
-            utils::message::fatal "missing --source or --layout, please see --help for detail."
+            dotf::utils::message::fatal "missing --source or --layout, please see --help for detail."
         fi
     fi
     if [[ ! -f "${source}" ]]; then
-        utils::message::fatal "'%s' not exists." "${source}"
+        dotf::utils::message::fatal "'%s' not exists." "${source}"
     fi
 
     while read line; do
@@ -407,8 +583,8 @@ dotf_layout_sync_command() {
         local url="${parts[1]}"
         if [[ ! -d "${path}" ]]; then
             local msg="git clone '${url}' to '${path}'"
-            if utils::boolean::is_true "${dry_run}"; then
-                utils::message::warning "[Simulate] ${msg}"
+            if dotf::utils::boolean::is_true "${dry_run}"; then
+                dotf::utils::message::warning "[Simulate] ${msg}"
             else
                 echo "${msg}"
                 git clone "${url}" "${path}" && echo
@@ -447,6 +623,13 @@ parse_requirements() {
     case $action in
         -*) ;;
 
+        link)
+            action="link"
+            shift
+            dotf_link_parse_requirements "$@"
+            shift $#
+            ;;
+
         layout)
             action="layout"
             shift
@@ -471,6 +654,89 @@ parse_requirements() {
     while [[ $# -gt 0 ]]; do
         key="$1"
         case "$key" in
+
+            -?*)
+                printf "invalid option: %s\n" "$key" >&2
+                exit 1
+                ;;
+
+            *)
+                # :command.parse_requirements_case
+                # :command.parse_requirements_case_simple
+                printf "invalid argument: %s\n" "$key" >&2
+                exit 1
+
+                ;;
+
+        esac
+    done
+
+}
+
+# :command.parse_requirements
+dotf_link_parse_requirements() {
+    # :command.fixed_flags_filter
+    while [[ $# -gt 0 ]]; do
+        case "${1:-}" in
+            --help | -h)
+                long_usage=yes
+                dotf_link_usage
+                exit
+                ;;
+
+            *)
+                break
+                ;;
+
+        esac
+    done
+
+    # :command.command_filter
+    action="link"
+
+    # :command.parse_requirements_while
+    while [[ $# -gt 0 ]]; do
+        key="$1"
+        case "$key" in
+            # :flag.case
+            --delete | -D)
+
+                # :flag.case_no_arg
+                args['--delete']=1
+                shift
+                ;;
+
+            # :flag.case
+            --restow | -R)
+
+                # :flag.case_no_arg
+                args['--restow']=1
+                shift
+                ;;
+
+            # :flag.case
+            --adopt)
+
+                # :flag.case_no_arg
+                args['--adopt']=1
+                shift
+                ;;
+
+            # :flag.case
+            --simulate | -n)
+
+                # :flag.case_no_arg
+                args['--simulate']=1
+                shift
+                ;;
+
+            # :flag.case
+            --verbose | -v)
+
+                # :flag.case_no_arg
+                args['--verbose']=1
+                shift
+                ;;
 
             -?*)
                 printf "invalid option: %s\n" "$key" >&2
@@ -794,6 +1060,7 @@ run() {
     parse_requirements "${input[@]}"
 
     case "$action" in
+        "link") dotf_link_command ;;
         "layout") dotf_layout_command ;;
         "layout git") dotf_layout_git_command ;;
         "layout sync") dotf_layout_sync_command ;;
